-- MySQL Script generated by MySQL Workbench
-- Sat Nov  3 21:33:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categoria_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria_producto` (
  `idCategoriaProducto` INT NOT NULL,
  `nombreCategoria` VARCHAR(30) NULL,
  PRIMARY KEY (`idCategoriaProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `idProductos` INT NOT NULL,
  `nombreProducto` VARCHAR(60) NULL,
  `idCategoriaProducto` INT NULL,
  `stock` INT NULL,
  `stockCritico` INT NULL,
  `stockMaximo` INT NULL,
  PRIMARY KEY (`idProductos`),
  CONSTRAINT `categoriaProducto_producto`
    FOREIGN KEY (`idCategoriaProducto`)
    REFERENCES `mydb`.`categoria_producto` (`idCategoriaProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comuna` (
  `idComuna` INT NOT NULL,
  `nombreComuna` VARCHAR(30) NULL,
  PRIMARY KEY (`idComuna`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedor` (
  `idProveedor` INT NOT NULL,
  `rutProveedor` VARCHAR(9) NULL,
  `nombreProveedor` VARCHAR(60) NULL,
  `direccion` VARCHAR(60) NULL,
  `fono` INT NULL,
  `contacto` VARCHAR(30) NULL,
  `email` VARCHAR(30) NULL,
  `comuna` INT NULL,
  PRIMARY KEY (`idProveedor`),
  CONSTRAINT `comuna_proveedor`
    FOREIGN KEY (`comuna`)
    REFERENCES `mydb`.`comuna` (`idComuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto_proveedor` (
  `idProveedor` INT NOT NULL,
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`idProveedor`, `idProducto`),
  CONSTRAINT `producto_productoProveedor`
    FOREIGN KEY (`idProducto`)
    REFERENCES `mydb`.`productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `proveedor_productoProveedor`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `mydb`.`proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `idClientes` INT NOT NULL,
  `rut` VARCHAR(9) NULL,
  `dirección` VARCHAR(60) NULL,
  `fonoFijo` INT NULL,
  `fonoCelular` INT NULL,
  `nombre` VARCHAR(30) NULL,
  `deudaTotal` INT NULL,
  `deudaMaxima` INT NULL,
  `apellidoPaterno` VARCHAR(30) NULL,
  `apellidoMaterno` VARCHAR(30) NULL,
  `idComuna` INT NULL,
  PRIMARY KEY (`idClientes`),
  UNIQUE INDEX `idClientes_UNIQUE` (`idClientes` ASC) VISIBLE,
  CONSTRAINT `comuna_clientes`
    FOREIGN KEY (`idComuna`)
    REFERENCES `mydb`.`comuna` (`idComuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`precio_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`precio_producto` (
  `idProducto` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `precioCosto` INT NULL,
  `precioVenta` INT NULL,
  PRIMARY KEY (`idProducto`, `fecha`),
  CONSTRAINT `producto_precioProducto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `mydb`.`productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medio_de_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medio_de_pago` (
  `idMedioPago` INT NOT NULL,
  `nombreMedioPago` VARCHAR(30) NULL,
  PRIMARY KEY (`idMedioPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idUsuario` INT NOT NULL,
  `nombreUsuario` VARCHAR(30) NULL,
  `pass` VARCHAR(8) NULL,
  `email` VARCHAR(40) NULL,
  `fono` INT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`abono_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`abono_cliente` (
  `idCliente` INT NOT NULL,
  `fechaPago` DATE NOT NULL,
  `monto` INT NULL,
  `idUsuario` INT NULL,
  PRIMARY KEY (`idCliente`, `fechaPago`),
  CONSTRAINT `cliente_abonoCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_abonoCliente`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`caja` (
  `idUsuario` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `montoInicial` INT NULL,
  `montoFinal` INT NULL,
  `saldoCaja` INT NULL,
  PRIMARY KEY (`idUsuario`, `fecha`),
  CONSTRAINT `usuario_caja`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venta` (
  `idVenta` INT NOT NULL,
  `montoVenta` INT NULL,
  `folioBoleta` INT NULL,
  `fechaVenta` DATE NULL,
  `idMedioPago` INT NULL,
  `idCliente` INT NULL,
  `idUsuario` INT NULL,
  PRIMARY KEY (`idVenta`),
  CONSTRAINT `mediopago_venta`
    FOREIGN KEY (`idMedioPago`)
    REFERENCES `mydb`.`medio_de_pago` (`idMedioPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cliente_venta`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_venta`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_venta` (
  `idVenta` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `cantidad` INT NULL,
  `precioUnitario` INT NULL,
  PRIMARY KEY (`idVenta`, `idProducto`),
  CONSTRAINT `venta_detalleVenta`
    FOREIGN KEY (`idVenta`)
    REFERENCES `mydb`.`venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producto_detalleVenta`
    FOREIGN KEY (`idProducto`)
    REFERENCES `mydb`.`productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'jptapia5' IDENTIFIED BY 'JPTapia123';

GRANT ALL ON `mydb`.* TO 'jptapia5';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
